# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='emial',
            new_name='email',
        ),
    ]
